apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  labels:
    app: flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-container
        image: dhivyadhub/maven: 3  #   Build and push your image locally (e.g., using Docker)
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_ENV
          value: production
        - name: APP_PORT
          value: "5000"
